#
# https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-dns
# Get-AzLocation | select location | sort-object location
#

locals {
  #Pull from excel
  private_dns_zones     = {
    privatelink-azure-automation-net = "privatelink.azure-automation.net" 
    privatelink-database-windows-net = "privatelink.database.windows.net"
    #privatelink-{dnsPrefix}-database-windows-net = "privatelink.{dnsPrefix}.database.windows.net"
    privatelink-sql-azuresynapse-net = "privatelink.sql.azuresynapse.net"
    privatelink-sql-azuresynapse-net = "privatelink.sql.azuresynapse.net"
    privatelink-dev-azuresynapse-net = "privatelink.dev.azuresynapse.net"
    privatelink-azuresynapse-net = "privatelink.azuresynapse.net"
    privatelink-blob-core-windows-net = "privatelink.blob.core.windows.net"
    privatelink-table-core-windows-net = "privatelink.table.core.windows.net"
    privatelink-queue-core-windows-net = "privatelink.queue.core.windows.net"
    privatelink-file-core-windows-net = "privatelink.file.core.windows.net"
    privatelink-web-core-windows-net = "privatelink.web.core.windows.net"
    privatelink-dfs-core-windows-net = "privatelink.dfs.core.windows.net"
    privatelink-documents-azure-com = "privatelink.documents.azure.com"
    privatelink-mongo-cosmos-azure-com = "privatelink.mongo.cosmos.azure.com"
    privatelink-cassandra-cosmos-azure-com = "privatelink.cassandra.cosmos.azure.com"
    privatelink-gremlin-cosmos-azure-com = "privatelink.gremlin.cosmos.azure.com"
    privatelink-table-cosmos-azure-com = "privatelink.table.cosmos.azure.com"
    privatelink-batch-azure-com = "privatelink.batch.azure.com"
    privatelink-batch-azure-com = "privatelink.batch.azure.com"
    privatelink-postgres-database-azure-com = "privatelink.postgres.database.azure.com"
    privatelink-mysql-database-azure-com = "privatelink.mysql.database.azure.com"
    privatelink-mariadb-database-azure-com = "privatelink.mariadb.database.azure.com"
    privatelink-vaultcore-azure-net = "privatelink.vaultcore.azure.net"
    privatelink-managedhsm-azure-net = "privatelink.managedhsm.azure.net"
    privatelink-centralus-azmk8s-io = "privatelink.centralus.azmk8s.io"
    #{subzone}-privatelink-centralus-azmk8s-io = "{subzone}.privatelink.centralus.azmk8s.io"
    privatelink-search-windows-net = "privatelink.search.windows.net"
    privatelink-azurecr-io = "privatelink.azurecr.io"
    centralus-privatelink-azurecr-io = "centralus.privatelink.azurecr.io"
    privatelink-azconfig-io = "privatelink.azconfig.io"
    privatelink-centralus-backup-windowsazure-com = "privatelink.centralus.backup.windowsazure.com"
    privatelink-siterecovery-windowsazure-com = "privatelink.siterecovery.windowsazure.com"
    privatelink-servicebus-windows-net = "privatelink.servicebus.windows.net"
    privatelink-servicebus-windows-net = "privatelink.servicebus.windows.net"
    privatelink-azure-devices-net = "privatelink.azure-devices.net"
    privatelink-servicebus-windows-net1 = "privatelink.servicebus.windows.net1"
    privatelink-azure-devices-provisioning-net = "privatelink.azure-devices-provisioning.net"
    privatelink-servicebus-windows-net = "privatelink.servicebus.windows.net"
    privatelink-eventgrid-azure-net = "privatelink.eventgrid.azure.net"
    privatelink-eventgrid-azure-net = "privatelink.eventgrid.azure.net"
    privatelink-azurewebsites-net = "privatelink.azurewebsites.net"
    scm-privatelink-azurewebsites-net = "scm.privatelink.azurewebsites.net"
    privatelink-api-azureml-ms = "privatelink.api.azureml.ms"
    privatelink-notebooks-azure-net = "privatelink.notebooks.azure.net"
    privatelink-service-signalr-net = "privatelink.service.signalr.net"
    privatelink-monitor-azure-com = "privatelink.monitor.azure.com"
    privatelink-oms-opinsights-azure-com = "privatelink.oms.opinsights.azure.com"
    privatelink-ods-opinsights-azure-com = "privatelink.ods.opinsights.azure.com"
    privatelink-agentsvc-azure-automation-net = "privatelink.agentsvc.azure-automation.net"
    privatelink-blob-core-windows-net = "privatelink.blob.core.windows.net"
    privatelink-cognitiveservices-azure-com = "privatelink.cognitiveservices.azure.com"
    privatelink-openai-azure-com = "privatelink.openai.azure.com"
    centralus-privatelink-afs-azure-net = "centralus.privatelink.afs.azure.net"
    privatelink-datafactory-azure-net = "privatelink.datafactory.azure.net"
    privatelink-adf-azure-com = "privatelink.adf.azure.com"
    privatelink-redis-cache-windows-net = "privatelink.redis.cache.windows.net"
    privatelink-redisenterprise-cache-azure-net = "privatelink.redisenterprise.cache.azure.net"
    privatelink-purview-azure-com = "privatelink.purview.azure.com"
    privatelink-purviewstudio-azure-com = "privatelink.purviewstudio.azure.com"
    privatelink-digitaltwins-azure-net = "privatelink.digitaltwins.azure.net"
    privatelink-azurehdinsight-net = "privatelink.azurehdinsight.net"
    privatelink-his-arc-azure-com = "privatelink.his.arc.azure.com"
    privatelink-guestconfiguration-azure-com = "privatelink.guestconfiguration.azure.com"
    privatelink-kubernetesconfiguration-azure-com = "privatelink.kubernetesconfiguration.azure.com"
    privatelink-media-azure-net = "privatelink.media.azure.net"
    privatelink-centralus-kusto-windows-net = "privatelink.centralus.kusto.windows.net"
    privatelink-azurestaticapps-net = "privatelink.azurestaticapps.net"
    #privatelink-{partitionId}-azurestaticapps-net = "privatelink.{partitionId}.azurestaticapps.net"
    privatelink-prod-migration-windowsazure-com = "privatelink.prod.migration.windowsazure.com"
    privatelink-azure-api-net = "privatelink.azure-api.net"
    privatelink-analysis-windows-net = "privatelink.analysis.windows.net"
    privatelink-pbidedicated-windows-net = "privatelink.pbidedicated.windows.net"
    privatelink-tip1-powerquery-microsoft-com = "privatelink.tip1.powerquery.microsoft.com"
    privatelink-directline-botframework-com = "privatelink.directline.botframework.com"
    privatelink-token-botframework-com = "privatelink.token.botframework.com"
    privatelink-workspace-azurehealthcareapis-com = "privatelink.workspace.azurehealthcareapis.com"
    privatelink-fhir-azurehealthcareapis-com = "privatelink.fhir.azurehealthcareapis.com"
    privatelink-dicom-azurehealthcareapis-com = "privatelink.dicom.azurehealthcareapis.com"
    privatelink-azuredatabricks-net = "privatelink.azuredatabricks.net"
    privatelink-global-wvd-microsoft-com = "privatelink-global.wvd.microsoft.com"
    privatelink-wvd-microsoft-com = "privatelink.wvd.microsoft.com"
  }
}

resource "azurerm_private_dns_zone" "private_dns_zones" {
  for_each            = local.private_dns_zones
  name                = each.value
  resource_group_name = azurerm_resource_group.rg.name
  tags                = var.tags
}
